import time
import sys
import colorama
from colorama import Fore
colorama.init()
print("Pythintosh created by skull._.python")
time.sleep(0.5)
print(Fore.GREEN + "Enter any key to boot up")
a = input("")
time.sleep(0.25)
un = input("Enter username: ")
while un != "admin":
    print("Incorrect username, try again")
    un = input("Enter username: ")
p = input("Enter password: ")
while p != "123":
    print("Incorrect password, try again")
    p = input("Enter password: ")
time.sleep(0.75)
print("Pythintosh booting up")
time.sleep(0.5)
print("Pythintosh has booted up successfully with no errors")
time.sleep(0.25)
print("Welcome to Pythintosh, " + un)
time.sleep(0.25)
print("For a list of commands, enter: list of commands")
c = input("")
while c not in ["add", "addition", "sub", "subtraction", "mul", "multiplication", "div", "division", "system specifications", "sys specs","list of commands", "shut down"]:
    print("Invalid command, try again")
    c = input("")
while c == "list of commands":
    print("Enter one of the following commands:", "add or addition,", "sub or subtraction,", "mul or multiplication,", "div or division,", "system specifications or sys specs,", "shut down")
    c = input("")
while c == "addition":
    print("Enter first number:")
    fa = float(input())
    print("Enter second number:")
    sa = float(input())
    time.sleep(0.5)
    print("Answer:")
    print(fa + sa)
    c = input("")
while c == "add":
    print("Enter first number:")
    fa = float(input())
    print("Enter second number:")
    sa = float(input())
    time.sleep(0.5)
    print("Answer:")
    print(fa + sa)
    c = input("")
while c == "subtraction":
    print("Enter number to be subtracted:")
    fs = float(input())
    print("Enter number to subtract from:")
    ss = float(input())
    time.sleep(0.5)
    print("Answer:")
    print(fs - ss)
    c = input("")
while c == "sub":
    print("Enter number to be subtracted:")
    fs = float(input())
    print("Enter number to subtract from:")
    ss = float(input())
    time.sleep(0.5)
    print("Answer:")
    print(fs - ss)
    c = input("")
while c == "mul":
    print("Enter first number:")
    fm = float(input())
    print("Enter second number:")
    sm = float(input())
    time.sleep(0.5)
    print("Answer:")
    print(fm * sm)
    c = str(input(""))
while c == "multiplication":
    print("Enter first number:")
    fm = float(input())
    print("Enter second number:")
    sm = float(input())
    time.sleep(0.5)
    print("Answer:")
    print(fm* sm)
    c = input("")
while c == "division":
    print("Enter number to be divided:")
    fd = float(input())
    print("Enter second number:")
    sd = float(input())
    while sd == 0:
        print("Cannot divide by zero, enter a non-zero number")
        sd = float(input("Enter second number: "))
    time.sleep(0.5)
    print("Answer:")
    print(fd / sd)
    c = input("")
while c == "div":
    print("Enter number to be divided:")
    fd = float(input())
    print("Enter second number:")
    sd = float(input())
    while sd == 0:
        print("Cannot divide by zero, enter a non-zero number")
        sd = float(input("Enter second number: "))
    time.sleep(0.5)
    print("Answer:")
    print(fd / sd)
    c = input("")
while c == "system specifications":
    time.sleep(0.25)
    print("Storage: 4096 bytes")
    time.sleep(0.5)
    print("OS: Pythintosh 3.2 ")
    time.sleep(0.25)
    print("Made with Visual Studio Code")
    c = input("")
while c == "sys specs":
    time.sleep(0.25)
    print("Storage: 4096 bytes")
    time.sleep(0.5)
    print("OS: Pythintosh 3.2 ")
    time.sleep(0.25)
    print("Made with Visual Studio Code")
    c = input("")
while c == "shut down":
    time.sleep(2)
    print("turning of background processes")
    time.sleep(0.75)
    print("shutting down")
    sys.exit
    c = 0